import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {createClient,type InArgs} from '@libsql/client/node';
import {Hono} from 'hono';
import {setD1Binding,type D1Database} from '../db/client.js';
import {splitSqlStatements} from '../db/split-sql.js';
import {signToken} from '../auth/jwt.js';
import {walletRoutes} from '../wallet/routes.js';
import {orderRoutes} from '../orders/routes.js';
import {creditWallet} from '../wallet/service.js';
import {settingsRoutes} from '../settings/routes.js';
import {getPaymentMethods} from './settings.js';
import {startOrderPayout,reconcileOrderPayouts} from '../payments/order-payout.js';

test('restored API preserves modern schema, wallet ownership and sandbox isolation',async () => {
 const client=createClient({url:'file::memory:'});
 for(const file of readdirSync('src/db/migrations').filter(f=>f.endsWith('.sql')).sort()) {
  for(const sql of splitSqlStatements(readFileSync(join('src/db/migrations',file),'utf8'))) await client.execute(sql);
 }
 setD1Binding({prepare(sql:string){return {args:[] as unknown[],bind(...args:unknown[]){this.args=args;return this;},async all(){const r=await client.execute({sql,args:this.args as InArgs});return {results:r.rows,success:true,meta:{changes:r.rowsAffected,last_row_id:Number(r.lastInsertRowid??0)}};}};}} as unknown as D1Database);
 const previousSecret=process.env.JWT_SECRET;process.env.JWT_SECRET='rollback-tests-only';
 try {
  await client.execute("INSERT INTO users (id,phone,name,password_hash,role,wallet_balance,wallet_balance_sandbox) VALUES ('customer','customer','Customer','hash','customer',10000,20000),('owner','owner','Owner','hash','customer',30000,40000)");
  await client.execute("INSERT INTO settings(key,value) VALUES('platform_environment','sandbox')");
  await client.execute("INSERT INTO wallets(id,owner_id,name,balance,balance_sandbox) VALUES('secondary','owner','Secondary',5000,6000)");
  await client.execute("INSERT INTO wallet_shares(id,owner_id,grantee_id,status,wallet_id) VALUES('share','owner','customer','active','secondary')");
  await client.execute("INSERT INTO lists(id,customer_id,title,status,environment) VALUES('list','customer','Test','draft','sandbox')");
  await client.execute("INSERT INTO orders(id,list_id,customer_id,stage,type,estimated_total,environment) VALUES('order','list','customer','Match','parcel',1000,'sandbox')");
  const token=await signToken({sub:'customer',role:'customer'});
  const app=new Hono();app.route('/v1',orderRoutes);app.route('/v1',walletRoutes);app.route('/v1',settingsRoutes);
  const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  assert.equal((await app.request('/v1/wallet/shares',{headers})).status,410);
  const denied=await app.request('/v1/orders/order/fund',{method:'POST',headers,body:JSON.stringify({paymentMethod:'wallet',useWallet:true,walletOwnerId:'owner'})});
  assert.equal(denied.status,400);
  await creditWallet('customer',1000,{type:'topup',environment:'sandbox'});
  const row=(await client.execute("SELECT wallet_balance,wallet_balance_sandbox FROM users WHERE id='customer'")).rows[0];
  assert.deepEqual([row.wallet_balance,row.wallet_balance_sandbox],[10000,21000]);
  assert.equal((await client.execute("SELECT balance FROM wallets WHERE id='secondary'")).rows[0].balance,5000);
  assert.equal((await app.request('/v1/wallet',{headers})).status,410);
  await client.execute("INSERT INTO users (id,phone,name,password_hash,role,admin_role) VALUES ('admin','admin','Admin','hash','admin','super_admin'),('ops','ops','Ops','hash','admin','operations_manager')");
  const adminToken=await signToken({sub:'admin',role:'admin'});
  const opsToken=await signToken({sub:'ops',role:'admin'});
  const save=(methods:string[],auth=adminToken)=>app.request('/v1/admin/settings',{method:'PUT',headers:{...headers,Authorization:`Bearer ${auth}`},body:JSON.stringify({paymentMethods:methods})});
  assert.deepEqual(await getPaymentMethods(),['cash'],'cash alone is enabled by default');
  assert.equal((await save([])).status,400,'cannot disable both');
  assert.deepEqual(await getPaymentMethods(),['cash']);
  assert.equal((await save(['cash','cash'])).status,400);
  assert.equal((await save(['mobile_money'],opsToken)).status,403,'requires payment management permission');
  assert.equal((await save(['cash','mobile_money'])).status,200);
  const create=(paymentRail?:string)=>app.request('/v1/orders',{method:'POST',headers,body:JSON.stringify({listId:'list',type:'shopping',destinationArea:'Kampala',estimatedTotal:1000,...(paymentRail?{paymentRail}:{})})});
  const cash=await create();assert.equal(cash.status,201);
  const cashBody=await cash.json();
  assert.equal(cashBody.order.payment_rail,'float','cash remains the default when both are active');
  assert.equal((await save(['mobile_money'])).status,200);
  assert.equal((await create('float')).status,409,'stale clients cannot choose disabled cash');
  assert.equal((await save([])).status,400);
  assert.deepEqual(await getPaymentMethods(),['mobile_money']);
  await Promise.all([save(['cash']),save(['mobile_money'])]);
  assert.equal((await getPaymentMethods()).length,1,'concurrent saves leave a nonempty atomic choice');
  const log=(await client.execute("SELECT after_json FROM admin_activity_log WHERE action='settings.update' ORDER BY rowid DESC LIMIT 1")).rows[0];
  assert.ok(JSON.parse(String(log.after_json)).paymentMethods.length > 0);
  await client.execute("UPDATE users SET role='rider' WHERE id='owner'");
  await client.execute("INSERT INTO riders(user_id,momo_msisdn,wallet_balance_sandbox) VALUES('owner','0772345678',7000)");
  const riderToken=await signToken({sub:'owner',role:'rider'});
  const riderHeaders={...headers,Authorization:`Bearer ${riderToken}`};
  await client.execute({sql:"UPDATE orders SET stage='Handover',rider_id='owner' WHERE id=?",args:[cashBody.order.id]});
  assert.equal((await app.request(`/v1/orders/${cashBody.order.id}/settle`,{method:'POST',headers:riderHeaders})).status,200,'cash completes without wallet or mobile-money transfer');
  assert.equal((await client.execute({sql:"SELECT COUNT(*) AS count FROM payments WHERE order_id=?",args:[cashBody.order.id]})).rows[0].count,0);
  await client.execute("INSERT INTO orders(id,list_id,customer_id,rider_id,stage,type,payment_rail,environment) VALUES('payout','list','customer','owner','Handover','shopping','escrow','sandbox'),('uncertain','list','customer','owner','Handover','parcel','escrow','sandbox'),('historical','list','customer','owner','Settle','parcel','escrow','sandbox')");
  for (const id of ['payout','uncertain','historical']) await client.execute({sql:"INSERT INTO payments(id,order_id,type,provider,amount,status) VALUES(?,?,'collection','yo_mock',10000,'successful')",args:[`col_${id}`,id]});
  await client.execute("INSERT INTO order_fees(order_id,service_fee,processing_fee_customer,processing_fee_rider,delivery_commission) VALUES('payout',500,200,300,1000)");
  let sent=0;
  const send=async () => {sent++;return {provider:'yo_mock' as const,providerRef:'test-reference',network:'mtn_momo' as const};};
  const [first,duplicate]=await Promise.all([startOrderPayout('payout',send),startOrderPayout('payout',send)]);
  assert.equal(first.id,duplicate.id);assert.equal(sent,1,'concurrent completion sends one payout');
  assert.equal(first.amount,8000,'honor the existing fee breakdown');
  assert.equal(first.status,'pending','not paid until provider confirms');
  assert.equal((await client.execute("SELECT wallet_balance_sandbox FROM riders WHERE user_id='owner'")).rows[0].wallet_balance_sandbox,7000,'no credit to rider wallet');
  await client.execute("UPDATE payments SET updated_at=datetime('now','-10 minutes') WHERE id LIKE 'payout_payout_%'");
  await reconcileOrderPayouts(async () => 'successful');
  assert.equal((await startOrderPayout('payout',send)).status,'successful');assert.equal(sent,1);
  assert.equal((await app.request('/v1/orders/payout/settle',{method:'POST',headers:riderHeaders})).status,200);
  assert.equal((await app.request('/v1/orders/payout/settle',{method:'POST',headers:riderHeaders})).status,409,'completed order cannot be settled twice');
  let uncertainSent=0;
  const uncertain=async () => {uncertainSent++;throw new Error('connection lost after submission');};
  const unknown=await startOrderPayout('uncertain',uncertain);
  assert.equal(unknown.status,'pending');assert.equal(unknown.provider_ref,null);
  await startOrderPayout('uncertain',uncertain);assert.equal(uncertainSent,1,'an uncertain transfer is never sent again');
  await assert.rejects(startOrderPayout('historical',send),/Historical/);
  await client.execute({sql:"UPDATE payments SET status='failed' WHERE id=?",args:[String(unknown.id)]});
  await startOrderPayout('uncertain',send);assert.equal(sent,2,'retry only after a confirmed failure');
  await client.execute("INSERT INTO orders(id,list_id,customer_id,rider_id,stage,type,payment_rail,environment) VALUES('partial','list','customer','owner','Handover','parcel','escrow','sandbox')");
  await client.execute("INSERT INTO payments(id,order_id,type,provider,amount,status) VALUES('partial-col','partial','collection','yo_mock',10000,'successful'),('partial-paid','partial','disbursement','yo_mock',3000,'successful')");
  assert.equal((await startOrderPayout('partial',send)).amount,7000,'older successful disbursements cannot be paid twice');
  assert.equal((await client.execute("SELECT wallet_balance_sandbox FROM riders WHERE user_id='owner'")).rows[0].wallet_balance_sandbox,7000);
  await client.execute("INSERT INTO orders(id,list_id,customer_id,rider_id,stage,type,payment_rail,estimated_total,environment) VALUES('charge-once','list','customer','owner','Match','parcel','escrow',6500,'sandbox')");
  const charge=()=>app.request('/v1/orders/charge-once/fund',{method:'POST',headers,body:JSON.stringify({msisdn:'0772345678'})});
  const charged=await Promise.all([charge(),charge()]);
  assert.deepEqual(charged.map(response=>response.status).sort(),[200,409]);
  assert.equal((await client.execute("SELECT COUNT(*) AS count FROM payments WHERE order_id='charge-once' AND provider_ref IS NOT NULL")).rows[0].count,1,'a double tap starts one charge');
  await client.execute("INSERT INTO lists(id,customer_id,title,status,environment) VALUES('live-list','customer','Live','draft','live')");
  await save(['mobile_money']);
  await client.execute("INSERT OR REPLACE INTO settings(key,value) VALUES('payments_active_providers','[\"flutterwave\"]')");
  const unavailable=await app.request('/v1/orders',{method:'POST',headers,body:JSON.stringify({listId:'live-list',type:'shopping',destinationArea:'Kampala',paymentRail:'escrow',estimatedTotal:1000})});
  assert.equal(unavailable.status,409,'do not collect live funds when the selected provider cannot pay riders');
 } finally {setD1Binding(undefined);client.close();if(previousSecret===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=previousSecret;}
});
